### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by tai960519073** [cookfish/segvoice#4]
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    vadSeg(model, dialogue)
  File "/Users/xiaomingtai/Downloads/segvoice-master/seg.py", line 41, in vadSeg
    segment(gmm_path,'tmp.wav')
  File "/Users/xiaomingtai/Downloads/segvoice-master/seg.py", line 86, in segment
    out_wav.extend(sig[f[0]*fs:f[1]*fs])
TypeError: slice indices must be integers or None or have an __index__ method
执行python main.py seg train_A.mdl A.wav 时，报错，请问什么问题？

**Comment by cookfish** [comment]
要在项目目录里执行 相对路径才是正确的

**Comment by tai960519073** [comment]
> 要在项目目录里执行 相对路径才是正确的

不行，依然报相同错误
